# Generated by Django 6.0.4 on 2026-04-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_actor_director_movie_actors_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster/'),
        ),
    ]
